name: Minecraft Server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Download Minecraft Server
      run: |
        wget -O server.jar https://launcher.mojang.com/v1/objects/your-minecraft-server-version/server.jar

    - name: Run Minecraft Server
      run: |
        echo "eula=true" > eula.txt
        java -Xmx1024M -Xms1024M -jar server.jar nogui
